[package]
name = "music-note"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Music theory library with midi, notes, chords, scales, and more"
repository = "https://github.com/matthunz/music-theory"

[lib]
name = "music_note"

[dependencies]
num-traits = "0.2.14"
