[package]
name = "staff"
version = "0.9.0"
edition = "2021"
license = "MIT"
description = "Music theory library with midi, notes, chords, scales, and more"
repository = "https://github.com/staff-rs/staff"
homepage = "https://staff-rs.github.io"

[features]
std = []
cli = ["anyhow", "clap", "svg"]
render = []
svg = ["dep:font-kit", "dep:rusttype", "dep:svg", "dep:text-svg"]
serde = ["dep:serde"]
default = ["render", "std", "svg", "serde", "rodio", "rand"]

[lib]
name = "staff"

[[bin]]
name = "staff"
required-features = ["cli"]

[dependencies]
num-traits = "0.2.14"
anyhow = { version = "1.0.61", optional = true }
thiserror = "1.0"
font-kit = { version = "0.11.0", optional = true }
rusttype = { version = "0.9.3", optional = true }
svg = { version = "0.12.1", optional = true }
text-svg = { version = "0.1.2", optional = true }
wasm-bindgen = { version = "0.2.83", optional = true }
rodio = { version = "0.16.0", optional = true }
rand = { version = "0.8.5", optional = true }

[dependencies.clap]
version = "4.0.18"
features = ["derive"]
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]
optional = true
