[package]
name = "staff"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "Music theory library with midi, notes, chords, scales, and more"
repository = "https://github.com/matthunz/staff"

[features]
cli = ["anyhow", "clap"]

[lib]
name = "staff"

[[bin]]
name = "staff"
required-features = ["cli"]

[dependencies]
num-traits = "0.2.14"
anyhow = { version = "1.0.61", optional = true }
thiserror = "1.0"

[dependencies.clap]
version = "4.0.18"
features = ["derive"]
optional = true
